---
  - name: install nginx
    package:
      name: nginx
      state: present

  - name: disable default website
    template:
      dest: /etc/nginx/nginx.conf
      src: nginx.conf.j2
      setype: httpd_config_t

  - name: enable nginx service
    systemd:
      name: nginx
      enabled: yes
