---
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: disable default website
    ansible.builtin.template:
      dest: /etc/nginx/nginx.conf
      src: nginx.conf.j2
      setype: httpd_config_t

  - name: enable nginx service
    ansible.builtin.systemd:
      name: nginx
      enabled: yes
