---
  - name: Install Fail2Ban packages
    ansible.builtin.package:
      name: "{{ fail2ban }}"
      state: present

  - name: Copy jail.conf before altering it
    ansible.builtin.copy:
      dest: /etc/fail2ban/jail.d/local.conf
      src: /etc/fail2ban/jail.conf
      remote_src: yes
      force: no

  - name: Configure Fail2Ban
    community.general.ini_file:
      path: /etc/fail2ban/jail.d/local.conf
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    loop:
    - { section: DEFAULT, option: bantime, value: 1w }
    - { section: sshd,    option: enabled, value: "true" }

  - name: Enable Fail2Ban Services
    ansible.builtin.systemd:
      daemon_reload: yes
      name: fail2ban
      enabled: yes
      state: restarted
