---
  - name: Install required Python packages for WattMan
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python3-cairo
      - python3-setuptools
      - python3-matplotlib-gtk3

  - name: Fix Radeon GPU Flicker
    cron:
      name: AMDGPU
      state: present
      special_time: reboot
      job: "echo high > /sys/class/drm/card0/device/power_dpm_force_performance_level && echo high > /sys/class/drm/card1/device/power_dpm_force_performance_level"
