---
## Install LibreNMS MySQL/MariaDB SNMP Extend - https://docs.librenms.org/Extensions/Applications/#mysql
# sudo wget https://github.com/librenms/librenms-agent/raw/master/snmp/mysql -O /etc/snmp/mysql && sudo chmod +x /etc/snmp/mysql
  - name: LibreNMS - MySQL/MariaDB SNMP Extend Script
    block:
    - name: Get Required Packages - MySQL/MariaDB SNMP Extend Script
      package:
        name: [ php-cli, php-mysql ]
        state: present
    - name: Get LibreNMS - MySQL/MariaDB Extend Script
      get_url:
        url: https://github.com/librenms/librenms-agent/raw/master/snmp/mysql
        dest: /etc/snmp/mysql
        mode: +x
        force: yes
    - name: Add LibreNMS - Create MySQL/MariaDB cache folder
      file:
        path: /var/cache/librenms/
        state: directory
        mode: '755'
        owner: "{{ snmpd_user }}"
        group: "{{ snmpd_group }}"

    - name: Add LibreNMS - MySQL/MariaDB SNMP Extend Script to snmpd.conf
      lineinfile:
        path: /etc/snmp/snmpd.conf
        regexp: '^extend mysql'
        line: extend mysql /etc/snmp/mysql
    when: "'mysql-server' in ansible_facts.packages or 'mariadb-server' in ansible_facts.packages"


