---
  - name: Add LibreNMS - APT Periodic Update for OS Update SNMP Extend Script
    lineinfile:
      path: /etc/apt/apt.conf.d/10periodic
      regexp: '^APT::Periodic'
      line: 'APT::Periodic::Update-Package-Lists "1";'
      create: yes
    when: ansible_os_family == 'Debian'

## TODO RHEL based OS - Will need SELinux settings
