---
  - name: Install SNMPD
    package:
      name: "{{ snmp_package }}"

  - name: Get LibreNMS - SNMP Extend Script
    shell: cat /etc/snmp/snmpd.conf
    register: snmpd_conf

  - name: Get LibreNMS - snmpd script
    template:
      src: snmpd.j2
      dest: /etc/snmp/snmpd.conf
      force: yes
    when: snmpd_conf.stdout.find('An example configuration') != -1
    notify: restart snmpd

  - name: Get LibreNMS - distro SNMP Extend Script
    get_url:
      url: https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro
      dest: /usr/bin/distro
      mode: +x
      force: yes
