---
  - name: Install Python Packages
    ansible.builtin.package:
      name:
      - python3
      - python3-pip
      state: present

  - name: upgrade pip
    ansible.builtin.pip:
      name: pip
      state: latest

  - name: Install pip packages
    ansible.builtin.pip:
      name:
      - netmiko
      - black
      - ipython

