---
# sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
  - name: Add VS Code GPG
    ansible.builtin.rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc
    when: ansible_os_family == 'RedHat'

# sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
  - name: Add VS Code Repo (RHEL)
    ansible.builtin.yum_repository:
      name: vscode
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgcheck: yes
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      file: vscode
    when: ansible_os_family == 'RedHat'

  - name: Install Visual Studio Code
    ansible.builtin.package:
      name: code
      state: present

