---
- import_tasks: librenms/apache-stats.yml
- import_tasks: librenms/bind-stats.yml
- import_tasks: librenms/mdadm.yml
- import_tasks: librenms/mysql-mariadb.yml
- import_tasks: librenms/nfs-server.yml
- import_tasks: librenms/ntp-server.yml
- import_tasks: librenms/os-update.yml
- import_tasks: librenms/php-fpm.yml
- import_tasks: librenms/snmpd-defaults.yml