---

## Install php Reports for CentOS 7

  - name: Install remote repo - remi-php
    ansible.builtin.package:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present

  - name: Enable Remi-PHP Repo
    ansible.builtin.yum_repository:
      name: remi-php73
      description: Remi's PHP 7.3 RPM repository for Enterprise Linux $releasever - $basearch
      mirrorlist: http://cdn.remirepo.net/enterprise/$releasever/php73/mirror
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi
      gpgcheck: yes
      enabled: yes

  - name: Install PHP Packages
    ansible.builtin.package:
      name:
      - php-fpm
      - php-cli
      - php-common
      - php-curl
      - php-gd
      - php-mbstring
      - php-process
      - php-snmp
      - php-xml
      - php-zip
      - php-memcached
      - php-mysqlnd
      - python-memcached
      state: present
    notify: restart php-fpm
