---
  - name: Define LibreNMS within Nginx
    ansible.builtin.template:
      dest: /etc/nginx/conf.d/librenms.conf
      src: librenms.conf.j2
      setype: httpd_config_t
    vars:
      port: 80
      server_name: "{{ ansible_host }}"
    notify: restart nginx
