---
  - name: Install PIP Packages
    pip:
      name:
      - mccabe<0.7,>=0.6
      - six~=1.12
      - toml>=0.7.1
      - lazy_object_proxy==1.4.*
      - typed-ast<1.5,>=1.4.0
      - wrapt~=1.11
      - astroid<=2.5,>=2.4.0
      - isort<5,>=4.2.5
      - pylint
      state: present
