---
  - name: Install packaged for pip
    ansible.builtin.package:
      name:
        - python3-pip
        - python3-virtualenv
        - python3-setuptools
      state: present

  - name: Install PIP Packages
    ansible.builtin.pip:
      name:
      - redis
      - python3-memcached
      - mccabe<0.7,>=0.6
      - six~=1.12
      - toml>=0.7.1
      - lazy_object_proxy==1.4.*
      - typed-ast<1.5,>=1.4.0
      - wrapt~=1.11
      - astroid<=2.5,>=2.4.0
      - isort<5,>=4.2.5
      - pylint
      executable: pip3
      state: present
