---
  - name: Create link to lnms command
    ansible.builtin.file:
      src: /opt/librenms/lnms
      dest: /usr/local/bin/lnms
      state: link

  - name: Copy lnms auto completion script
    ansible.builtin.copy:
      src: /opt/librenms/misc/lnms-completion.bash
      dest: /etc/bash_completion.d/
      remote_src: yes
